name: QEMU

on:
  pull_request:
    branches:
      - main
      - maintenance/**

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.11

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  multi_platform:
    if: "github.repository == 'andyfaff/numpy'"
    runs-on: ubuntu-latest
    strategy:
        matrix:
          platform:
            - [s390x, "VX VXE VXE2"]
            - [ppc64le, "VSX VSX2 VSX3"]
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.15.0
      env:
        # configure cibuildwheel to build native archs ('auto'), and some
        # emulated ones
        CIBW_ARCHS_LINUX: ${{ matrix.platform[0] }}
        CIBW_BUILD: cp311-*
        CIBW_CONFIG_SETTINGS: "setup-args=-Dallow-noblas=true"
        CIBW_ENVIRONMENT_LINUX: EXPECT_CPU_FEATURES="${{ matrix.platform[1] }}"

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
